theme: jekyll-theme-minimal
author: Cevdet Arda Haran
email: cevdet@tutamail.com
title: 3D Boxes Background
description: "3D Boxes Background Frontend Website Project."
keywords: "Cevdet Arda Haran, Cennedy, 3d boxes background, 3d, boxes"
baseurl: "/3d-boxes-background"
url: "https://cevdetardaharan.github.io/3d-boxes-background"
twitter_username: cevdetardaharan  
github_username:  cevdetardaharan
